config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todos
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :date, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :first_act, only: [:edit, :destroy, :update]

  def index
    @todos = Todo.all.order(date: :asc)
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "You've added an event."
      redirect_to root_path
    else
      flash[:alert] = "The grid can't be blank!"
      redirect_to root_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update_attributes(todo_params)
      redirect_to todos_url
      flash[:notice] = "List updated."
    else
      render :action => :edit
    end
  end

  def destroy
    @todo.destroy
    flash[:notice] = "You've deleted an event."
    redirect_to todos_path
  end


  private

    def todo_params
      params.require(:todo).permit(:title, :date, :description)
    end

    def first_act
      @todo = Todo.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chieh's Todo App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  });
  </script>


  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/edit.html.erb
<div class="col-md-6">
  <h3>Edit a new todo:</h3>
<br>
  <div class="form container col-md-8 col-md-offset-2">
    <%= form_for @todo do |f| %>

      <div class= "form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class= "form-group">
        <%= f.label :date, "Date" %>
        <%= f.text_field :date, class: "form-control" %>
      </div>
      <div class= "form-group">
        <%= f.label :description, "Detail" %>
        <%= f.text_area :description, class: "form-control"%>
      </div>
        <%= f.submit "Update", class: "btn btn-danger btn-sm" %>
      
     <% end %>
     <br>
     <%= link_to "Back to Index", todos_path %>
  </div>
</div>

app/views/todos/index.html.erb
<h1>Have something to do?</h1>
<br>
<hr>
  <div class="col-md-4">
    <h3>Add a new todo:</h3>
    <div class="form-group col-md-10">
      <%= form_with scope: :todo, url: todos_path do |f| %>

        <div class= "form-group">
          <%= f.label :title, "Title" %>
          <%= f.text_field :title, class: "form-control", placeholder: "ex. Take out garbage." %>
        </div>
        <div class= "form-group">
          <%= f.label :date, "Date" %>
          <%= f.text_field :date, class: "form-control", placeholder: "ex. 2018-01-01" %>
        </div>
        <div class= "form-group">
          <%= f.label :description, "Detail" %>
          <%= f.text_area :description, class: "form-control"%>
        </div>
          <%= f.submit "Create", class: "btn btn-success btn-sm" %>
          
     <% end %>
       
    </div>

  </div>

  <div class="col-md-8">
    <h3>Here's your todo list</h3><br>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %><br>
    <table class="table table-hover">
      <% @todos.each do |todo| %>
        <tr>
          <td><b><%= todo.title %></b></td>
          <td>
            <small>
              
              <%=link_to 'Edit', edit_todo_path(todo) %>
              <%= link_to 'Delete', todo_path(todo), method: :delete, data:{confirm: "Are you sure you want to delete this event?"} %>
                
            </small> 
          </td>
          <td><%= todo.date %></td>
          <td><i><%= todo.description %></i></td>
        </tr>

      <% end %>   
    </table>
    
  </div>